# -*- coding: utf-8 -*-
"""performance_test_filled.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13t2QrBJq8qt_nMUskVx9HbXD0iovWk0b

# Math Problem Performance Test

This notebook tests the model on problems from problems.csv and analyzes performance by problem type and difficulty.
"""

import os

repo_path = 'probing-llm-math'
if not os.path.exists(repo_path):
    !git clone --branch performance-test https://github.com/1hamzaiqbal/probing-llm-math.git
else:
    print(f"Repository '{repo_path}' already exists.")

"""## Setup and Model Loading"""

!pip install -q transformers accelerate pandas seaborn matplotlib tqdm
import torch
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.auto import tqdm
from transformers import AutoTokenizer, AutoModelForCausalLM

# === Display configuration: show full text in DataFrames/prints ===
pd.set_option("display.max_colwidth", None)   # don't truncate long strings
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

# Load model and tokenizer
model_name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
print(f"Loading model: {model_name}...")

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    dtype=torch.float16
)

print("✅ Model loaded successfully!")

"""## Load Problems Dataset"""

# Load problems from CSV
df = pd.read_csv('/content/probing-llm-math/data/problems.csv')

print(f"Dataset shape: {df.shape}")
print(f"\nColumns: {df.columns.tolist()}")
print(f"\nTopics: {df['topic'].unique()}")
print(f"\nDifficulty levels: {df['difficulty'].unique()}")
print(f"\nProblems per topic-difficulty combination:")
print(df.groupby(['topic', 'difficulty']).size())

# Display first few problems
print("\nFirst few problems:")
df.head()

"""## Run Performance Test

Evaluate the model on a subset of problems. Start with a small sample to test, then increase.
"""

import math

SEED = 42
SAMPLE_SIZE = 15  # total number of problems you actually want

required = {'question', 'answer', 'topic', 'difficulty'}
missing = required - set(df.columns)
if missing:
    raise ValueError(f"Missing columns in df: {sorted(missing)}")

# stratified sample up to SAMPLE_SIZE total
group_cols = ['topic', 'difficulty']
gb = df.groupby(group_cols, dropna=False)
num_groups = len(gb)

if SAMPLE_SIZE >= len(df):
    eval_df = df.sample(frac=1, random_state=SEED).reset_index(drop=True)
else:
    # allocate 1 per group until we hit SAMPLE_SIZE, else proportional
    if SAMPLE_SIZE <= num_groups:
        # pick SAMPLE_SIZE groups at random, 1 from each
        chosen_groups = (
            gb.size()
              .sample(n=SAMPLE_SIZE, random_state=SEED)
              .index
        )
        parts = []
        for gkey in chosen_groups:
            g = gb.get_group(gkey)
            parts.append(g.sample(n=1, random_state=SEED))
        eval_df = pd.concat(parts, ignore_index=True)
    else:
        # proportional quotas (at least 1 if group non-empty)
        sizes = gb.size()
        weights = sizes / sizes.sum()
        base = (weights * SAMPLE_SIZE).round().astype(int)
        # ensure at least 1 where possible
        base = base.mask((sizes > 0) & (base == 0), 1)
        # adjust to exact total
        diff = SAMPLE_SIZE - base.sum()
        if diff != 0:
            order = (weights.sort_values(ascending=(diff < 0))
                              .index.tolist())
            for gkey in order:
                if diff == 0:
                    break
                step = 1 if diff > 0 else -1
                new_val = base.loc[gkey] + step
                if 0 <= new_val <= sizes.loc[gkey]:
                    base.loc[gkey] = new_val
                    diff -= step
        # sample per group
        parts = []
        for gkey, k in base.items():
            if k > 0:
                g = gb.get_group(gkey)
                parts.append(g.sample(n=min(k, len(g)), random_state=SEED))
        eval_df = pd.concat(parts, ignore_index=True)

print(f"Evaluating on {len(eval_df)} problems...")
if set(group_cols).issubset(eval_df.columns):
    print("Distribution:\n", eval_df.value_counts(group_cols).sort_index())
else:
    print("Skipping distribution print; stratifying columns not present in eval_df.")

eval_df

"""## Analysis by Topic and Difficulty"""

# Accuracy by topic
print("📊 Accuracy by Topic:")
topic_acc = eval_df.groupby('topic')['is_correct'].agg(['mean', 'sum', 'count'])
topic_acc.columns = ['accuracy', 'correct', 'total']
topic_acc['accuracy'] = topic_acc['accuracy'].apply(lambda x: f"{x:.2%}")
print(topic_acc)

# Accuracy by difficulty
print("\n📊 Accuracy by Difficulty:")
diff_acc = eval_df.groupby('difficulty')['is_correct'].agg(['mean', 'sum', 'count'])
diff_acc.columns = ['accuracy', 'correct', 'total']
diff_acc['accuracy'] = diff_acc['accuracy'].apply(lambda x: f"{x:.2%}")
print(diff_acc)

"""## Heatmap: Performance by Topic and Difficulty"""

# Create pivot table for heatmap
heatmap_data = eval_df.groupby(['topic', 'difficulty'])['is_correct'].mean().unstack(fill_value=np.nan)

# Reorder columns by difficulty
difficulty_order = ['Level 1', 'Level 2', 'Level 3', 'Level 4', 'Level 5']
heatmap_data = heatmap_data.reindex(columns=[col for col in difficulty_order if col in heatmap_data.columns])

# Create heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(
    heatmap_data,
    annot=True,
    fmt='.0%',
    cmap='RdYlGn',
    vmin=0,
    vmax=1,
    cbar_kws={'label': 'Accuracy'},
    linewidths=0.5,
    linecolor='gray',
    mask=heatmap_data.isna()
)

plt.title('Model Accuracy by Problem Type and Difficulty', fontsize=14, fontweight='bold')
plt.xlabel('Difficulty Level', fontsize=12)
plt.ylabel('Problem Topic', fontsize=12)
plt.tight_layout()
plt.show()

print("\n📊 Heatmap Data (Accuracy Matrix):")
print(heatmap_data)

"""## Additional Visualizations"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Bar chart: Accuracy by Topic
topic_acc_values = eval_df.groupby('topic')['is_correct'].mean().sort_values(ascending=False)
axes[0].bar(range(len(topic_acc_values)), topic_acc_values.values, color='steelblue', alpha=0.7)
axes[0].set_xticks(range(len(topic_acc_values)))
axes[0].set_xticklabels(topic_acc_values.index, rotation=45, ha='right')
axes[0].set_ylabel('Accuracy', fontsize=11)
axes[0].set_title('Accuracy by Topic', fontsize=12, fontweight='bold')
axes[0].set_ylim([0, 1])
axes[0].grid(axis='y', alpha=0.3)

for i, v in enumerate(topic_acc_values.values):
    axes[0].text(i, v + 0.02, f'{v:.1%}', ha='center', va='bottom', fontweight='bold')

# Bar chart: Accuracy by Difficulty
diff_acc_values = eval_df.groupby('difficulty')['is_correct'].mean()
level_order = ['Level 1', 'Level 2', 'Level 3', 'Level 4', 'Level 5']
diff_acc_values = diff_acc_values.reindex([l for l in level_order if l in diff_acc_values.index])

axes[1].bar(range(len(diff_acc_values)), diff_acc_values.values, color='coral', alpha=0.7)
axes[1].set_xticks(range(len(diff_acc_values)))
axes[1].set_xticklabels(diff_acc_values.index, rotation=45, ha='right')
axes[1].set_ylabel('Accuracy', fontsize=11)
axes[1].set_title('Accuracy by Difficulty Level', fontsize=12, fontweight='bold')
axes[1].set_ylim([0, 1])
axes[1].grid(axis='y', alpha=0.3)

for i, v in enumerate(diff_acc_values.values):
    axes[1].text(i, v + 0.02, f'{v:.1%}', ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.show()

"""## Capture Hidden States (Sample)

Capture hidden states for a sample of problems to analyze later. This can help understand what the model is learning.
"""

# Sample problems for hidden state capture
# Try to get a diverse sample: some correct, some incorrect, across topics and difficulties
HIDDEN_STATE_SAMPLE_SIZE = 15

# Get stratified sample
correct_samples = eval_df[eval_df['is_correct'] == True].sample(min(len(eval_df[eval_df['is_correct'] == True]), HIDDEN_STATE_SAMPLE_SIZE // 2), random_state=42)
incorrect_samples = eval_df[eval_df['is_correct'] == False].sample(min(len(eval_df[eval_df['is_correct'] == False]), HIDDEN_STATE_SAMPLE_SIZE // 2), random_state=42)
hidden_state_samples = pd.concat([correct_samples, incorrect_samples]).sample(frac=1, random_state=42).reset_index(drop=True)

print(f"Capturing hidden states for {len(hidden_state_samples)} problems...")
print(f"Distribution: {hidden_state_samples['is_correct'].value_counts().to_dict()}")

hidden_states_list = []
hidden_state_metadata = []

for idx, row in tqdm(hidden_state_samples.iterrows(), total=len(hidden_state_samples), desc="Capturing hidden states"):
    # Get hidden states by doing a forward pass on the question
    inputs = tokenizer(row['question'], return_tensors="pt")
    inputs = inputs.to(model.device)

    with torch.no_grad():
        outputs = model(**inputs, output_hidden_states=True, use_cache=False)
        hidden_states = outputs.hidden_states
        layer_hidden = [h.squeeze(0).detach().cpu().numpy() for h in hidden_states]
        layer_means = [h.mean(axis=0) for h in layer_hidden]

    hidden_states_list.append(layer_means)
    hidden_state_metadata.append({
        'id': row['id'],
        'topic': row['topic'],
        'difficulty': row['difficulty'],
        'is_correct': row['is_correct'],
        'question': row['question']
    })

# Convert to numpy array
hidden_states_array = np.array(hidden_states_list, dtype=np.float32)
print(f"\nHidden states shape: {hidden_states_array.shape}")
print(f"Format: (num_samples={hidden_states_array.shape[0]}, num_layers={hidden_states_array.shape[1]}, hidden_dim={hidden_states_array.shape[2]})")

# Save hidden states and metadata
np.savez_compressed(
    "performance_test_hidden_states.npz",
    hidden_states=hidden_states_array,
    metadata=np.array(hidden_state_metadata)
)

print("\n✅ Saved hidden states to 'performance_test_hidden_states.npz'")
print("   You can load this later for analysis with: np.load('performance_test_hidden_states.npz', allow_pickle=True)")

"""## Save Results"""

# Save evaluation results
eval_df.to_csv('performance_test_results.csv', index=False)
print("✅ Saved evaluation results to 'performance_test_results.csv'")

# Save accuracy matrix
heatmap_data.to_csv('performance_test_accuracy_matrix.csv')
print("✅ Saved accuracy matrix to 'performance_test_accuracy_matrix.csv'")

# Summary statistics
print("\n" + "="*60)
print("EVALUATION SUMMARY")
print("="*60)
print(f"Total problems evaluated: {len(eval_df)}")
print(f"Overall accuracy: {eval_df['is_correct'].mean():.2%}")

topic_summary = eval_df.groupby('topic')['is_correct'].mean()
if len(topic_summary) > 0:
    print(f"\nBest performing topic: {topic_summary.idxmax()} ({topic_summary.max():.2%})")
    print(f"Worst performing topic: {topic_summary.idxmin()} ({topic_summary.min():.2%})")

diff_summary = eval_df.groupby('difficulty')['is_correct'].mean()
if len(diff_summary) > 0:
    print(f"\nBest performing difficulty: {diff_summary.idxmax()} ({diff_summary.max():.2%})")
    print(f"Worst performing difficulty: {diff_summary.idxmin()} ({diff_summary.min():.2%})")
print("="*60)

"""## Example: View Some Results"""

# Show a few examples - some correct and some incorrect
print("Example correct answers:")
print("="*80)
for idx, row in eval_df[eval_df['is_correct'] == True].head(2).iterrows():
    print(f"\nProblem {row['id']} ({row['topic']}, {row['difficulty']})")
    print(f"Question: {row['question']}")
    print(f"Expected: {extract_boxed_answer(extract_model_answer(row))}")
    print(f"Model: {row['model_answer']}")
    print("-"*80)

print("\n\nExample incorrect answers:")
print("="*80)
for idx, row in eval_df[eval_df['is_correct'] == False].head(2).iterrows():
    print(f"\nProblem {row['id']} ({row['topic']}, {row['difficulty']})")
    print(f"Question: {row['question']}")
    print(f"Expected: {extract_boxed_answer(extract_model_answer(row))}")
    print(f"Model: {row['model_answer']}")
    print("-"*80)

# === Added Helpers: simple parsing + correctness (substring rule) ===
import re
from typing import List

def _latex_frac_to_str(s: str) -> str:
    """Convert simple LaTeX \frac{a}{b} forms into 'a/b' to aid matching."""
    if not isinstance(s, str):
        return ""
    def repl(m):
        a = re.sub(r"\s+", "", m.group(1))
        b = re.sub(r"\s+", "", m.group(2))
        return f"{a}/{b}"
    return re.sub(r"\\frac\s*\{\s*([^{}]+)\s*\}\s*\{\s*([^{}]+)\s*\}", repl, s)

def extract_answer_tokens(text: str) -> List[str]:
    """Return a list of number-like tokens from an answer string.
    Includes integers, decimals, percents (without %), and a/b fractions.
    Order is preserved and duplicates are removed.
    """
    if not isinstance(text, str):
        return []
    s = _latex_frac_to_str(text)
    s = s.replace("$", "")
    # drop explicit boxed region (we'll add its content separately)
    s = re.sub(r"\\boxed\s*\{[^{}]*\}", "", s)
    # fractions
    frac = re.findall(r"-?\d+\s*/\s*-?\d+", s)
    # decimals/integers
    nums = re.findall(r"-?\d+(?:\.\d+)?", s)
    # percents (keep token without %)
    perc = [p[:-1] for p in re.findall(r"-?\d+(?:\.\d+)?%", s)]
    tokens = [re.sub(r"\s+","", t) for t in (frac + perc + nums)]
    out, seen = [], set()
    for t in tokens:
        if t not in seen:
            seen.add(t); out.append(t)
    return out

def extract_boxed_answer(text: str) -> str:
    """If \boxed{...} is present, return its content normalized, else best-effort fallback token."""
    if not isinstance(text, str):
        return ""
    m = re.search(r"\\boxed\s*\{\s*([^{}]+?)\s*\}", text)
    if m:
        inner = _latex_frac_to_str(m.group(1))
        inner = re.sub(r"\\[a-zA-Z]+", "", inner)  # drop stray LaTeX commands
        inner = inner.replace("$", "")
        inner = re.sub(r"\s+", "", inner)
        return inner
    # fallback: last number-like token if any
    toks = extract_answer_tokens(text)
    return toks[-1] if toks else ""

def extract_gold_tokens(row) -> List[str]:
    """Pick the gold/expected answer text from typical columns and tokenize it."""
    # Try common column names for the ground-truth answer
    for key in ("answer", "expected", "ground_truth", "gold", "label"):
        if key in row and isinstance(row[key], str) and row[key].strip():
            text = row[key]
            break
    else:
        return []
    # Prefer boxed; include boxed first if present
    boxed = extract_boxed_answer(text)
    toks = extract_answer_tokens(text)
    # Put boxed first if it's not empty and not already present
    if boxed and boxed not in toks:
        toks = [boxed] + toks
    return toks

def extract_model_answer(row) -> str:
    """Compatibility shim for existing prints: return the *gold* answer text from the row.
    The original notebook prints `Expected: extract_boxed_answer(extract_model_answer(row))`.
    This function simply returns the ground-truth answer field so that usage continues to work.
    """
    for key in ("answer", "expected", "ground_truth", "gold", "label"):
        if key in row and isinstance(row[key], str):
            return row[key]
    return ""

def contains_any_token(haystack: str, tokens: List[str]) -> bool:
    """Return True if any token is found as a substring in `haystack` (very lenient by design)."""
    if not isinstance(haystack, str) or not tokens:
        return False
    s = _latex_frac_to_str(haystack)
    s = s.replace(" ", "").replace("$", "")
    # Very permissive rule: count correct if any gold token appears anywhere in the model answer.
    return any(t and (t in s) for t in tokens)

def compute_is_correct(eval_df):
    """Add an `is_correct` boolean column to `eval_df` using the lenient substring rule.
    If a model answer column is missing, this will create an empty one.
    """
    import pandas as _pd  # local import so this cell is self-contained
    if "is_correct" in eval_df.columns:
        return eval_df
    # find model answer column name
    model_col = None
    for c in ("model_answer", "prediction", "output", "response"):
        if c in eval_df.columns:
            model_col = c; break
    if model_col is None:
        model_col = "model_answer"
        eval_df[model_col] = ""
    eval_df["__gold_tokens__"] = eval_df.apply(lambda r: extract_gold_tokens(r), axis=1)
    eval_df["is_correct"] = eval_df.apply(lambda r: contains_any_token(str(r[model_col]), r["__gold_tokens__"]), axis=1)
    return eval_df

# === Simple evaluation + basic plots (matplotlib only) ===
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

if 'eval_df' not in globals():
    print("eval_df not found. Run the sampling/inference steps first.")
else:
    eval_df = compute_is_correct(eval_df)
    n = len(eval_df)
    overall_acc = float(eval_df['is_correct'].mean()) if n else float('nan')
    print(f"Overall accuracy (substring rule): {overall_acc:.3f}  (n={n})")

    # 1) Accuracy by topic
    if 'topic' in eval_df.columns:
        acc_by_topic = eval_df.groupby('topic')['is_correct'].mean().sort_values(ascending=False)
        print("\nAccuracy by topic:\n", acc_by_topic)
        plt.figure(figsize=(10, 4))
        acc_by_topic.plot(kind='bar')
        plt.title('Accuracy by Topic')
        plt.ylabel('Accuracy')
        plt.tight_layout()
        plt.show()

    # 2) Heatmap: topic x difficulty
    if {'topic','difficulty'}.issubset(eval_df.columns):
        def diff_key(x):
            m = re.search(r'(\d+)', str(x))
            return int(m.group(1)) if m else 10**9
        topics = sorted([str(t) for t in eval_df['topic'].dropna().unique()])
        diffs = sorted([str(d) for d in eval_df['difficulty'].dropna().unique()], key=diff_key)
        pivot = eval_df.pivot_table(index='topic', columns='difficulty', values='is_correct', aggfunc='mean') \                       .reindex(index=topics, columns=diffs)
        plt.figure(figsize=(max(6, 1 + 0.8*len(diffs)), max(5, 0.5*len(topics))))
        im = plt.imshow(pivot.values, aspect='auto')
        plt.colorbar(im, fraction=0.046, pad=0.04)
        plt.xticks(range(len(diffs)), diffs, rotation=45, ha='right')
        plt.yticks(range(len(topics)), topics)
        plt.title('Accuracy Heatmap (Topic × Difficulty)')
        plt.xlabel('Difficulty')
        plt.ylabel('Topic')
        plt.tight_layout()
        plt.show()

    # 3) Accuracy by difficulty
    if 'difficulty' in eval_df.columns:
        def diff_key(x):
            m = re.search(r'(\d+)', str(x))
            return int(m.group(1)) if m else 10**9
        acc_by_diff = eval_df.groupby('difficulty')['is_correct'].mean().sort_index(key=lambda s: s.map(diff_key))
        print("\nAccuracy by difficulty:\n", acc_by_diff)
        plt.figure(figsize=(8, 4))
        acc_by_diff.plot(kind='bar')
        plt.title('Accuracy by Difficulty')
        plt.ylabel('Accuracy')
        plt.tight_layout()
        plt.show()

    # 4) Optional: answer length vs correctness
    if 'model_answer' in eval_df.columns:
        eval_df['__answer_len__'] = eval_df['model_answer'].fillna('').map(len)
        y = eval_df['is_correct'].astype(int).values
        x = eval_df['__answer_len__'].values
        rng = np.random.default_rng(0)
        yj = y + (rng.random(size=len(y)) - 0.5) * 0.1
        plt.figure(figsize=(8, 4))
        plt.scatter(x, yj, s=10)
        plt.xlabel('Model answer length (chars)')
        plt.ylabel('Correct (1=yes) [jittered]')
        plt.title('Answer Length vs Correctness')
        plt.tight_layout()
        plt.show()

    # Save core outputs for convenience
    try:
        eval_df.to_csv('performance_test_results.csv', index=False)
        print("Saved: performance_test_results.csv")
    except Exception as e:
        print("Could not save performance_test_results.csv:", e)

