# -*- coding: utf-8 -*-
"""pipeline_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/1hamzaiqbal/probing-llm-math/blob/colab-pipeline-setup/pipeline_colab.ipynb

# Math LLM Probing & Evaluation Pipeline

This notebook implements a pipeline to:
1. Load `Qwen/Qwen2.5-Math-7B-Instruct`.
2. Generate answers to math problems (enforcing direct answers).
3. Extract hidden states.
4. Evaluate answers using Regex and SymPy.
"""

import os
import sys

# 1. Clone the repo if it doesn't exist
REPO_NAME = "probing-llm-math"
if not os.path.exists(REPO_NAME):
    print("Cloning repository...")
    !git clone -b colab-pipeline-setup https://github.com/1hamzaiqbal/probing-llm-math.git
else:
    print(f"{REPO_NAME} already exists.")

# 2. Install dependencies
print("Installing dependencies...")
!pip install -q -r {REPO_NAME}/requirements.txt

# 3. Add to path so we can import src
if REPO_NAME not in sys.path:
    sys.path.append(REPO_NAME)

print("Setup complete!")

try:
    from src import model_utils, evaluator
    print("Successfully imported modules from src.")
except ImportError as e:
    print(f"Error importing modules: {e}")
    print("Current path:", sys.path)
    print("Current dir contents:", os.listdir("."))
    if os.path.exists(REPO_NAME):
        print(f"{REPO_NAME} contents:", os.listdir(REPO_NAME))

# [OPTIONAL] Reset & Update
# Run this cell if you want to pull the latest code and free up VRAM without restarting the runtime.

import gc
import torch
import importlib
import sys

# 1. Free VRAM
print("Clearing VRAM...")
try:
    del model
    del tokenizer
except NameError:
    pass

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()
print("VRAM cleared.")

# 2. Pull latest code
print("Pulling latest code...")
!cd {REPO_NAME} && git pull

# 3. Reload modules
print("Reloading modules...")
import src.model_utils
import src.evaluator
importlib.reload(src.model_utils)
importlib.reload(src.evaluator)
from src import model_utils, evaluator

print("Modules reloaded. You can now re-run the 'Load Model' cell.")

# Load Model
# Use load_in_4bit=True for T4 GPUs to save VRAM and allow larger context
model, tokenizer = model_utils.load_model(model_name="Qwen/Qwen2.5-Math-7B-Instruct", load_in_4bit=True)

# # Define some test questions (Weird Formats & Hard Problems)
# questions = [
#     # Matrix Determinant (LaTeX array check)
#     {"question": "Compute the determinant of the matrix $\\begin{pmatrix} 1 & 2 \\\\ 3 & 4 \\end{pmatrix}$.", "answer": "-2"},

#     # Interval Notation (Set theory)
#     {"question": "Find the domain of $f(x) = \\sqrt{x-1}$.", "answer": "[1, \\infty)"},

#     # Coordinates (Tuple format)
#     {"question": "Find the intersection point of the lines $y=x$ and $y=2-x$.", "answer": "(1, 1)"},

#     # Hard Integral (Gaussian - Symbol check)
#     {"question": "Evaluate $\\int_{-\\infty}^{\\infty} e^{-x^2} dx$.", "answer": "\\sqrt{\\pi}"},

#     # Hard Number Theory (AIME 2001 #1 - Integer answer)
#     {"question": "Find the sum of all positive integers $n$ such that $n$ divides $n^2 + 1$.", "answer": "1"},

#     # Nested Surds (Weird LaTeX)
#     {"question": "Simplify \\sqrt{3 + 2\\sqrt{2}}.", "answer": "1+\\sqrt{2}"},

#     # Units / Physics Style
#     {"question": "If a car travels 60 miles in 2 hours, what is its average speed in mph?", "answer": "30"},

#     # Multiple Choice Style (Letter extraction)
#     {"question": "Which of the following is prime? (A) 4 (B) 9 (C) 11 (D) 15. Answer with the letter only.", "answer": "C"}
# ]

# # Run Pipeline
# results = []

# for item in questions:
#     q = item["question"]
#     gt = item["answer"]

#     print(f"Processing: {q}")

#     # Generate
#     pred_text, hidden_states, is_truncated = model_utils.generate_answer(model, tokenizer, q)

#     # Check truncation
#     if evaluator.check_truncation(pred_text, is_truncated):
#         print("  WARNING: Output truncated!")

#     # Extract clean answer
#     clean_pred = evaluator.extract_answer(pred_text)

#     # Evaluate
#     is_correct = evaluator.is_equivalent(clean_pred, gt)

#     # print(f"  Pred: {pred_text}") # Commented out to reduce clutter if needed
#     print(f"  Clean: {clean_pred}")
#     print(f"  Correct: {is_correct}")

#     results.append({
#         "question": q,
#         "ground_truth": gt,
#         "prediction": pred_text,
#         "clean_prediction": clean_pred,
#         "correct": is_correct,
#         "truncated": is_truncated
#     })

# # Analyze Results
# correct_count = sum(1 for r in results if r['correct'])
# accuracy = correct_count / len(results)
# print(f"Accuracy: {accuracy:.2%}")

"""# Linear Probing

This section runs the linear probing experiments.
1. Collect hidden states and correctness labels from GSM8K.
2. Train a logistic regression classifier to predict correctness.
3. Visualize the results.
"""

# # 1. Collect Data
# # We'll use the MATH dataset (all levels) and enforce balancing
# # to ensure we get both correct and incorrect answers.
# # Removing 'Level 5' filter to allow easier questions so we can find correct answers too.

# !python3 probing-llm-math/src/collect_probe_data.py --num_samples 5 --dataset math --balance --audit_file probe_audit.csv

# # [Optional] View Audit Log
# import pandas as pd
# if os.path.exists("probe_audit.csv"):
#     df_audit = pd.read_csv("probe_audit.csv")
#     display(df_audit.head(20))
#     print("\nClass Distribution:")
#     print(df_audit['is_correct'].value_counts())
# else:
#     print("Audit file not found.")

# SECOND MINI RUN
!python probing-llm-math/src/collect_probe_data.py \
    --num_samples 150 \
    --dataset math \
    --balance \
    --output_file probe_data.pt

import pandas as pd

# Load the audit file
if os.path.exists("probe_audit.csv"):
    df_audit = pd.read_csv("probe_audit.csv")

    # Filter for incorrect predictions
    incorrect_predictions = df_audit[df_audit['is_correct'] == False]

    print("Displaying incorrect predictions for manual review:")
    # Display relevant columns for manual review
    display(incorrect_predictions[['question', 'ground_truth', 'clean_prediction']])

    if incorrect_predictions.empty:
        print("No incorrect predictions found in probe_audit.csv.")
else:
    print("Audit file 'probe_audit.csv' not found. Please ensure it has been generated.")

# Load and analyze probe data
import torch
import pandas as pd
import numpy as np
from collections import Counter

# Load the data
data = torch.load("probe_data.pt")
print(f"Loaded {len(data)} samples")

# Basic stats
correct = sum(1 for d in data if d['is_correct'])
print(f"Correct: {correct}, Incorrect: {len(data) - correct}")

# Topic distribution
topics = Counter(d['topic'] for d in data)
print(f"\nTopic distribution: {dict(topics)}")

# Level distribution
levels = Counter(d['level_num'] for d in data)
print(f"Level distribution: {dict(sorted(levels.items()))}")

# Activation shapes
print(f"\nActivation shapes:")
print(f"  0%: {data[0]['activations_0pct'].shape}")
print(f"  50%: {data[0].get('activations_50pct', 'N/A')}")
print(f"  100%: {data[0]['activations_100pct'].shape}")

# Check for any issues
print(f"\nFirst few samples:")
for i, d in enumerate(data[:5]):
    print(f"  {i}: topic={d['topic']}, level={d['level_num']}, correct={d['is_correct']}")

# Check for potential evaluator false negatives
import re

df = pd.read_csv("probe_audit.csv")

print("Potential evaluator issues (wrong predictions that look close):")
print("="*60)

issues = []
for idx, row in df.iterrows():
    gt = str(row['ground_truth']).strip()
    pred = str(row['clean_prediction']).strip()

    if row['is_correct'] == False:
        # Check for formatting differences that should be equivalent
        gt_clean = re.sub(r'[_{}\\]', '', gt.lower())
        pred_clean = re.sub(r'[_{}\\]', '', pred.lower())

        if gt_clean == pred_clean:
            issues.append((idx, gt, pred, "Formatting mismatch"))
        elif gt.replace(" ", "") == pred.replace(" ", ""):
            issues.append((idx, gt, pred, "Whitespace mismatch"))
        # Check numeric close matches
        try:
            gt_num = float(gt)
            pred_num = float(pred)
            if abs(gt_num - pred_num) < 0.01:
                issues.append((idx, gt, pred, "Numeric near-match"))
        except:
            pass

print(f"Found {len(issues)} potential issues:")
for idx, gt, pred, issue_type in issues[:10]:
    print(f"  Row {idx}: GT='{gt}' vs Pred='{pred}' ({issue_type})")

# Save to Google Drive (run this if you want to persist)
from google.colab import drive
drive.mount('/content/drive')

import shutil
import os

# Create output directory
output_dir = "/content/drive/MyDrive/probe_results"
os.makedirs(output_dir, exist_ok=True)

# Copy files
shutil.copy("probe_data.pt", f"{output_dir}/probe_data.pt")
shutil.copy("probe_audit.csv", f"{output_dir}/probe_audit.csv")

print(f"Saved to {output_dir}")

# Train all probes on the collected data
!python probing-llm-math/src/train_probe.py \
    --data_file probe_data.pt \
    --output_dir probe_results

# Display probe results
from IPython.display import Image, display
import os

results_dir = "probe_results"

# Show all plots
for f in sorted(os.listdir(results_dir)):
    if f.endswith('.png'):
        print(f"\n{f}:")
        display(Image(filename=f"{results_dir}/{f}"))

# Show summary
import json
with open(f"{results_dir}/summary.json") as f:
    summary = json.load(f)

print("\n" + "="*50)
print("SUMMARY")
print("="*50)
for k, v in summary.items():
    print(f"  {k}: {v}")

# # FIRST MINI RUN
# # 1. Collect probe data (with all metadata)
# !python probing-llm-math/src/collect_probe_data.py \
#     --num_samples 10 \
#     --dataset math \
#     --balance \
#     --output_file probe_data.pt

# # 2. Train all probes
# !python probing-llm-math/src/train_probe.py \
#     --data_file probe_data.pt \
#     --output_dir probe_results

# # 3. Generate heatmap (separate run, more samples)
# !python probing-llm-math/src/stratified_eval.py \
#     --samples_per_cell 5 \
#     --output_dir eval_results



# import os
# from IPython.display import Image, display

# print("--- Evaluation Results ---")
# result_dir = "eval_results"

# # Print summary.txt content
# summary_path = os.path.join(result_dir, "summary.txt")
# if os.path.exists(summary_path):
#     with open(summary_path, "r") as f:
#         summary_text = f.read()
#     print(summary_text)
# else:
#     print(f"(summary not found at {summary_path})")

# # Visualize heatmap
# heatmap_path = os.path.join(result_dir, "accuracy_heatmap.png")
# if os.path.exists(heatmap_path):
#     print("Displaying accuracy heatmap:")
#     display(Image(filename=heatmap_path))
# else:
#     print(f"(heatmap not found at {heatmap_path})")

# # Optionally confirm number of results
# results_pt_path = os.path.join(result_dir, "results.pt")
# if os.path.exists(results_pt_path):
#     print(f"\nSaved results file exists: {results_pt_path}")
# else:
#     print("(results.pt not found)")

# # 2. Train Probes & Analyze

# !python3 probing-llm-math/src/train_probe.py

# # 3. Visualize Results
# from IPython.display import Image, display
# import os

# results_dir = "probe_results"
# if os.path.exists(results_dir):
#     print("Probe Accuracy by Layer:")
#     display(Image(filename=f"{results_dir}/probe_accuracy.png"))

#     # Check for PCA plot (might vary by layer index)
#     pca_files = [f for f in os.listdir(results_dir) if f.startswith("pca_layer")]
#     if pca_files:
#         print("PCA Visualization:")
#         display(Image(filename=f"{results_dir}/{pca_files[0]}"))
# else:
#     print("No results found. Did the training script run successfully?")

# Re-check predictions with fixed evaluator
import pandas as pd
import importlib

# Reload evaluator
import src.evaluator
importlib.reload(src.evaluator)
from src.evaluator import is_equivalent, extract_answer

df = pd.read_csv("probe_audit.csv")
new_correct = 0
changes = []

for idx, row in df.iterrows():
    gt = str(row['ground_truth'])
    pred = str(row['clean_prediction'])
    new_result = is_equivalent(pred, gt)
    if new_result != row.get('is_correct', False):
        changes.append((idx, gt, pred, new_result))
        if new_result:
            new_correct += 1

print(f"Found {len(changes)} changed evaluations ({new_correct} new correct)")
for idx, gt, pred, result in changes[:10]:
    print(f"  Row {idx}: {gt} vs {pred} -> {'✓' if result else '✗'}")

# Quick test with smaller model
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

model_name = "Qwen/Qwen2.5-Math-1.5B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    load_in_4bit=True,
    device_map="cuda"
)

# Test one problem
messages = [
    {"role": "system", "content": "Solve and put answer in \\boxed{}."},
    {"role": "user", "content": "What is 15% of 80?"}
]
text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
inputs = tokenizer(text, return_tensors="pt").to("cuda")
out = model.generate(**inputs, max_new_tokens=256)
print(tokenizer.decode(out[0], skip_special_tokens=True))

# Pull updates
!cd probing-llm-math && git pull

# Collect data with both pooling methods (default)
!python probing-llm-math/src/collect_probe_data.py \
    --num_samples 200 \
    --dataset math \
    --balance \
    --output_file probe_data_1.5b.pt \
    --seed 42

# Train probes (handles new format automatically)
!python probing-llm-math/src/train_probe.py \
    --data_file probe_data_1.5b.pt \
    --output_dir probe_results_1.5b

# Pull updates
!cd probing-llm-math && git pull

# Collect data with both pooling methods (default)
!python probing-llm-math/src/collect_probe_data.py \
    --num_samples 1000 \
    --dataset math \
    --balance \
    --output_file probe_data_1.5b_1000.pt \
    --seed 42

# Train probes (handles new format automatically)
!python probing-llm-math/src/train_probe.py \
    --data_file probe_data_1.5b_1000.pt \
    --output_dir probe_data_1.5b_1000

!python probing-llm-math/src/stratified_eval.py \
    --samples_per_cell 100 \
    --output_dir eval_results_1.5b_100

import shutil
shutil.copytree("probe_results_1.5b_1000", "/content/drive/MyDrive/probe_results_1.5b_1000", dirs_exist_ok=True)
shutil.copy("probe_data_1.5b_1000.pt", "/content/drive/MyDrive/probe_data_1.5b_1000.pt")
print("Saved to Drive!")

from google.colab import drive
drive.mount('/content/drive')

# Pull updates
!cd probing-llm-math && git pull

# Collect data with both pooling methods (default)
# ~1000 samples × 52s = ~14.5 hours
!python probing-llm-math/src/collect_probe_data.py \
    --num_samples 500 \
    --dataset math \
    --balance \
    --output_file probe_data_1.5b_1000.pt \
    --seed 42

# Train probes (handles new format automatically)
# FIX: output_dir was wrong (said probe_data not probe_results)
!python probing-llm-math/src/train_probe.py \
    --data_file probe_data_1.5b_1000.pt \
    --output_dir probe_results_1.5b_1000

# ⚠️ WARNING: 100 samples/cell × 4 topics × 5 levels = 2000 samples = ~29 MORE hours!
# Reduce to 20 samples/cell = 400 samples = ~6 hours
!python probing-llm-math/src/stratified_eval.py \
    --samples_per_cell 20 \
    --output_dir eval_results_1.5b

# Save to Drive
import shutil
shutil.copytree("probe_results_1.5b_1000", "/content/drive/MyDrive/probe_results_1.5b_1000", dirs_exist_ok=True)
shutil.copy("probe_data_1.5b_1000.pt", "/content/drive/MyDrive/probe_data_1.5b_1000.pt")
shutil.copytree("eval_results_1.5b", "/content/drive/MyDrive/eval_results_1.5b", dirs_exist_ok=True)
print("Saved to Drive!")

# Download audit log to view/analyze
from google.colab import files
files.download('probe_audit.csv')

# Or copy to Drive
import shutil
shutil.copy('probe_audit.csv', '/content/drive/MyDrive/probe_audit_500.csv')
print("Copied audit log to Drive!")

# Quick preview
import pandas as pd
df = pd.read_csv('probe_audit.csv')
print(f"Total samples: {len(df)}")
print(f"Correct: {df['is_correct'].sum()}")
print(f"Incorrect: {(~df['is_correct']).sum()}")
print("\nSample of incorrect predictions:")
print(df[df['is_correct'] == False][['topic', 'level', 'ground_truth', 'clean_prediction']].head(10))

# Force update in Colab
!cd probing-llm-math && git fetch origin && git reset --hard origin/colab-pipeline-setup

# Clear Python cache
import sys
for mod in list(sys.modules.keys()):
    if 'model_utils' in mod or 'stratified_eval' in mod or 'evaluator' in mod:
        del sys.modules[mod]

# Now run stratified eval
!python probing-llm-math/src/stratified_eval.py \
    --samples_per_cell 20 \
    --output_dir eval_results_1.5b

!cd probing-llm-math && git fetch origin && git reset --hard origin/colab-pipeline-setup

import pandas as pd
import importlib
import sys

# Clear cache
for mod in list(sys.modules.keys()):
    if 'evaluator' in mod:
        del sys.modules[mod]

# Import fresh
sys.path.insert(0, 'probing-llm-math/src')
from evaluator import is_equivalent, extract_answer

# Re-check all predictions
df = pd.read_csv('probe_audit.csv')
new_correct = 0
changes = []

for idx, row in df.iterrows():
    gt = str(row['ground_truth'])
    pred = str(row['clean_prediction'])
    old_result = row['is_correct']
    new_result = is_equivalent(pred, gt)

    if new_result != old_result:
        changes.append((idx, gt, pred, old_result, new_result))
        if new_result:
            new_correct += 1

print(f"Found {len(changes)} changed evaluations ({new_correct} new correct)")
for idx, gt, pred, old, new in changes[:15]:
    symbol = "✓" if new else "✗"
    print(f"  Row {idx}: {gt[:30]} vs {pred[:30]} -> {symbol}")

import torch

# Load existing data
loaded = torch.load('probe_data_1.5b_1000.pt')
data = loaded['data']
metadata = loaded['metadata']

# Update is_correct for each sample based on new evaluator
updated = 0
for d in data:
    gt = str(d['ground_truth'])
    pred = extract_answer(str(d['prediction']))
    new_correct = is_equivalent(pred, gt)
    if new_correct != d['is_correct']:
        d['is_correct'] = new_correct
        updated += 1

print(f"Updated {updated} labels")

# Count new balance
correct = sum(1 for d in data if d['is_correct'])
print(f"New balance: {correct} correct, {len(data) - correct} incorrect")

# Save corrected data
torch.save({'data': data, 'metadata': metadata}, 'probe_data_1.5b_500_fixed.pt')
print("Saved to probe_data_1.5b_500_fixed.pt")

!python probing-llm-math/src/train_probe.py \
    --data_file probe_data_1.5b_500_fixed.pt \
    --output_dir probe_results_1.5b_500_fixed

!cd probing-llm-math && git pull

# Analyze token counts
!python probing-llm-math/src/analyze_tokens.py \
    --audit_file probe_audit.csv \
    --output_dir token_analysis

# View the plots
from IPython.display import Image, display
import os
for f in sorted(os.listdir("token_analysis")):
    if f.endswith('.png'):
        print(f"\n{f}:")
        display(Image(f"token_analysis/{f}"))

!cd probing-llm-math && git pull

# Run confidence analysis
!python probing-llm-math/src/confidence_analysis.py \
    --data_file probe_data_1.5b_500_fixed.pt \
    --output_dir confidence_analysis \
    --layer 15

# View results
from IPython.display import Image, display
import os
for f in sorted(os.listdir("confidence_analysis")):
    if f.endswith('.png'):
        print(f"\n{f}:")
        display(Image(f"confidence_analysis/{f}"))

!cd probing-llm-math && git pull



!python probing-llm-math/src/train_probe.py \
    --data_file probe_data_1.5b_500_fixed.pt \
    --output_dir probe_results_mlp \
    --mlp

